//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string notes { get; set; }
        public string phone { get; set; }
        public string combany { get; set; }
        public string email { get; set; }
        public Nullable<bool> active { get; set; }
        public string image { get; set; }
    }
}
